// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateCaffeineBeverage(arg1:models.NewCaffeineBeverageInput):Promise<models.CaffeineBeverage>;

export function CreateCaffeineIntake(arg1:models.NewCaffeineIntakeInput):Promise<models.CaffeineIntake>;

export function DeleteCaffeineBeverage(arg1:number):Promise<void>;

export function DeleteCaffeineIntake(arg1:number):Promise<void>;

export function GetAllCaffeineBeverages(arg1:boolean):Promise<Array<models.CaffeineBeverage>>;

export function GetCaffeineBeverage(arg1:number):Promise<models.CaffeineBeverage>;

export function GetCaffeineIntake(arg1:number):Promise<models.CaffeineIntake>;

export function GetCaffeineIntakeByDay(arg1:string):Promise<Array<models.CaffeineIntake>>;

export function GetCaffeineIntakeRange(arg1:string,arg2:string):Promise<Array<models.CaffeineIntake>>;

export function GetDailyCaffeineTotal(arg1:string):Promise<Record<string, any>>;

export function UpdateCaffeineBeverage(arg1:number,arg2:models.UpdateCaffeineBeverageInput):Promise<models.CaffeineBeverage>;

export function UpdateCaffeineIntake(arg1:number,arg2:models.UpdateCaffeineIntakeInput):Promise<models.CaffeineIntake>;
