// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCaffeineBeverage(arg1) {
  return window['go']['api']['CaffeineController']['CreateCaffeineBeverage'](arg1);
}

export function CreateCaffeineIntake(arg1) {
  return window['go']['api']['CaffeineController']['CreateCaffeineIntake'](arg1);
}

export function DeleteCaffeineBeverage(arg1) {
  return window['go']['api']['CaffeineController']['DeleteCaffeineBeverage'](arg1);
}

export function DeleteCaffeineIntake(arg1) {
  return window['go']['api']['CaffeineController']['DeleteCaffeineIntake'](arg1);
}

export function GetAllCaffeineBeverages(arg1) {
  return window['go']['api']['CaffeineController']['GetAllCaffeineBeverages'](arg1);
}

export function GetCaffeineBeverage(arg1) {
  return window['go']['api']['CaffeineController']['GetCaffeineBeverage'](arg1);
}

export function GetCaffeineIntake(arg1) {
  return window['go']['api']['CaffeineController']['GetCaffeineIntake'](arg1);
}

export function GetCaffeineIntakeByDay(arg1) {
  return window['go']['api']['CaffeineController']['GetCaffeineIntakeByDay'](arg1);
}

export function GetCaffeineIntakeRange(arg1, arg2) {
  return window['go']['api']['CaffeineController']['GetCaffeineIntakeRange'](arg1, arg2);
}

export function GetDailyCaffeineTotal(arg1) {
  return window['go']['api']['CaffeineController']['GetDailyCaffeineTotal'](arg1);
}

export function UpdateCaffeineBeverage(arg1, arg2) {
  return window['go']['api']['CaffeineController']['UpdateCaffeineBeverage'](arg1, arg2);
}

export function UpdateCaffeineIntake(arg1, arg2) {
  return window['go']['api']['CaffeineController']['UpdateCaffeineIntake'](arg1, arg2);
}
