// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllData(arg1) {
  return window['go']['api']['DatabaseController']['ClearAllData'](arg1);
}
