// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteHabit(arg1, arg2) {
  return window['go']['api']['HabitController']['CompleteHabit'](arg1, arg2);
}

export function CreateHabit(arg1) {
  return window['go']['api']['HabitController']['CreateHabit'](arg1);
}

export function DeleteHabit(arg1) {
  return window['go']['api']['HabitController']['DeleteHabit'](arg1);
}

export function GetAllHabits() {
  return window['go']['api']['HabitController']['GetAllHabits']();
}

export function GetHabit(arg1) {
  return window['go']['api']['HabitController']['GetHabit'](arg1);
}

export function GetHabitLogs(arg1, arg2, arg3) {
  return window['go']['api']['HabitController']['GetHabitLogs'](arg1, arg2, arg3);
}

export function LogHabit(arg1, arg2) {
  return window['go']['api']['HabitController']['LogHabit'](arg1, arg2);
}

export function UncompleteHabit(arg1, arg2) {
  return window['go']['api']['HabitController']['UncompleteHabit'](arg1, arg2);
}

export function UpdateHabit(arg1, arg2) {
  return window['go']['api']['HabitController']['UpdateHabit'](arg1, arg2);
}
