// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMoodEntry(arg1) {
  return window['go']['api']['MoodController']['CreateMoodEntry'](arg1);
}

export function DeleteMoodEntry(arg1) {
  return window['go']['api']['MoodController']['DeleteMoodEntry'](arg1);
}

export function GetAllMoodEntries(arg1, arg2) {
  return window['go']['api']['MoodController']['GetAllMoodEntries'](arg1, arg2);
}

export function GetMoodEntry(arg1) {
  return window['go']['api']['MoodController']['GetMoodEntry'](arg1);
}

export function GetMoodEntryByDate(arg1) {
  return window['go']['api']['MoodController']['GetMoodEntryByDate'](arg1);
}

export function UpdateMoodEntry(arg1, arg2) {
  return window['go']['api']['MoodController']['UpdateMoodEntry'](arg1, arg2);
}
