// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateMoodEntry(arg1:models.NewMoodEntryInput):Promise<models.MoodEntry>;

export function DeleteMoodEntry(arg1:number):Promise<void>;

export function GetAllMoodEntries(arg1:string,arg2:string):Promise<Array<models.MoodEntry>>;

export function GetMoodEntry(arg1:number):Promise<models.MoodEntry>;

export function GetMoodEntryByDate(arg1:string):Promise<models.MoodEntry>;

export function UpdateMoodEntry(arg1:number,arg2:models.UpdateMoodEntryInput):Promise<models.MoodEntry>;
