// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCaffeineStats(arg1:string):Promise<Record<string, any>>;

export function GetCorrelationStats():Promise<Record<string, any>>;

export function GetHabitStats(arg1:number,arg2:string):Promise<Record<string, any>>;

export function GetMoodStats(arg1:string):Promise<Record<string, any>>;
