// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCaffeineStats(arg1) {
  return window['go']['api']['StatsController']['GetCaffeineStats'](arg1);
}

export function GetCorrelationStats() {
  return window['go']['api']['StatsController']['GetCorrelationStats']();
}

export function GetHabitStats(arg1, arg2) {
  return window['go']['api']['StatsController']['GetHabitStats'](arg1, arg2);
}

export function GetMoodStats(arg1) {
  return window['go']['api']['StatsController']['GetMoodStats'](arg1);
}
